Symbols = {
    r'\to': '→',
    r'\dto': '⇒',
    r'\dot': '∙',
    r'\inf': '∞',
    r'\and': '∧',
    r'\or': '∨',
    r'\alpha': 'α',
    r'\betta': 'β',
    r'\lbd': 'λ',
    r'\gam': 'γ',
    r'\delta': 'δ',
    r'\Delta': 'Δ',
    r'\eps': 'ε',
    r'\zeta': 'ζ',
    r'\eta': 'η',
    r'\theta': 'θ',
    r'\mu': 'μ',
    r'\nu': 'ν',
    r'\xi': 'ξ',
    r'\pi': 'π',
    r'\sigma': 'σ',
    r'\Sigma': 'Σ',
    r'\tau': 'τ',
    r'\phi': 'φ',
    r'\psi': 'ψ',
    r'\omega': 'ω',
    r'\a': '∀',
    r'\e': '∃',
    r'\ne': '∄',
    r'\r': 'ℝ',
    r'\in': '∈',
    r'\leq': '≤',
    r'\geq': '≥',
    r'\neq': '≠'
}

